name: Post Release to Discord

on:
  workflow_call:
    inputs:
      github_event:
        required: true
        type: object
  workflow_dispatch:

jobs:
  post_to_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send release to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "content": "New Release: **${{ github_event.release.name }}**\n${{ github_event.release.body }}\nCheck it out here: ${{ github_event.release.html_url }}"
            }' \
            $DISCORD_WEBHOOK
