name: Post Release to Discord

on:
  workflow_call:
    inputs:
      release_name:
        description: "Name of the release"
        required: true
        type: string
      release_body:
        description: "Body of the release notes"
        required: true
        type: string
      release_html_url:
        description: "URL to the release on GitHub"
        required: true
        type: string
jobs:
  post_to_discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send release to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{
              "content": "New Release: **${{ inputs.release_name }}**\n${{ inputs.release_body }}\nCheck it out here: ${{ inputs.release_html_url }}"
            }' \
            $DISCORD_WEBHOOK
